GET https://r2swydpx7syeiycnrnny67bxii0myurm.lambda-url.us-east-1.on.aws/
?phrase=The quick brown fox jumps over the lazy dog
&ascii=true


###

POST https://r2swydpx7syeiycnrnny67bxii0myurm.lambda-url.us-east-1.on.aws/
Content-Type: application/json

{
  "phrase": "V2FsdHosIGJhZCBueW1waCwgZm9yIHF1aWNrIGppZ3MgdmV4Lg=="
}