version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "handex-chord-phrase"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qlums2i4zjzc"
s3_prefix = "handex-chord-phrase"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
