GET https://l7c5uk7cutnfql5j4iunvx4fuq0yjfbs.lambda-url.us-east-1.on.aws/
?phrase=The quick brown fox jumps over the lazy dog
&ascii=true


###

POST https://l7c5uk7cutnfql5j4iunvx4fuq0yjfbs.lambda-url.us-east-1.on.aws/
Content-Type: application/json

{
  "phrase": "V2FsdHosIGJhZCBueW1waCwgZm9yIHF1aWNrIGppZ3MgdmV4Lg=="
}