AWSTemplateFormatVersion: 2010-09-09
Description: chord-phrase
Transform:
- AWS::Serverless-2016-10-31
Resources:
  chordPhrase:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chord-phrase
      Handler: src/handlers/phrase.phraseHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
      - AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowMethods:
          - POST
          - GET
          AllowOrigins:
          - https://handex.io
          - http://localhost
      CodeUri: chordPhrase
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.chordPhrase47900af3DepLayer
    Metadata:
      SamResourceId: chordPhrase
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: D:\T3\Projects\self\Handex\chord-phrase\.aws-sam\auto-dependency-layer\adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  lambdaUrl:
    Description: URL for the Lambda function
    Value:
      Fn::GetAtt:
      - chordPhraseUrl
      - FunctionUrl
